[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/v1/*"
  to = "https://tlm-temp-api.onrender.com/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/broadcasting/auth"
  to = "https://tlm-temp-api.onrender.com/broadcasting/auth"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200